"""The registry lock file, `toolpacks/registry.lock.yaml`.

The lock maps every `tool@major` to the manifest that provides it, the image
repository and digest, and a hash of the manifest content. It is generated
from the manifests by `glow toolpack lock` and checked in CI with `--check`,
so a manifest edit cannot reach the registry without a lock update.
"""

from pathlib import Path, PurePosixPath
from typing import Annotated

import yaml
from pydantic import Field, StringConstraints, field_validator
from pydantic import ValidationError as ModelError

from glow.builtins import BUILTINS
from glow.manifests import MANIFEST_FILENAME, load_manifest, split_image
from glow.models.common import StrictModel
from glow.models.toolpack import ToolpackName
from glow.validation import (
    DocumentReadError,
    format_path,
    parse_yaml,
    read_document,
    yaml_error_message,
)

LOCK_FILENAME = "registry.lock.yaml"
LOCK_HEADER = "# Generated by `glow toolpack lock` from */manifest.yaml. Do not edit by hand.\n"

UsesKey = Annotated[
    str,
    StringConstraints(
        pattern=r"^[a-z][a-z0-9_]*(\.[a-z][a-z0-9_]*)+@[1-9][0-9]{0,5}$", max_length=128
    ),
]
Digest = Annotated[str, StringConstraints(pattern=r"^sha256:[0-9a-f]{64}$")]
Sha256Hex = Annotated[str, StringConstraints(pattern=r"^[0-9a-f]{64}$")]


class LockError(Exception):
    """The lock file is missing, malformed, or does not match the manifests."""


class LockEntry(StrictModel):
    toolpack: ToolpackName
    manifest: str = Field(description="Manifest path relative to the toolpacks directory.")
    image: Annotated[str, StringConstraints(min_length=1, max_length=512)]
    digest: Digest | None = Field(description="Image digest; null for a local development image.")
    manifest_sha256: Sha256Hex

    @field_validator("manifest")
    @classmethod
    def _relative_path(cls, value: str) -> str:
        # The registry opens this path; keep it inside the toolpacks directory.
        path = PurePosixPath(value)
        if path.is_absolute() or ".." in path.parts or path.name != MANIFEST_FILENAME:
            raise ValueError(f"must be a relative path to a {MANIFEST_FILENAME} without '..'")
        return value


class LockFile(StrictModel):
    tools: dict[UsesKey, LockEntry]


def lock_path(root: Path) -> Path:
    return root / LOCK_FILENAME


def discover_manifests(root: Path) -> list[Path]:
    if not root.is_dir():
        raise LockError(f"{root} is not a directory")
    return sorted(root.glob(f"*/{MANIFEST_FILENAME}"))


def build_lock(root: Path) -> LockFile:
    """Build the lock from every `<root>/*/manifest.yaml`.

    Raises `ManifestError` or `DocumentReadError` for a bad manifest and
    `LockError` when two manifests provide the same `tool@major`.
    """
    entries: dict[str, LockEntry] = {}
    for path in discover_manifests(root):
        loaded = load_manifest(path)
        manifest = loaded.manifest
        relative = path.relative_to(root).as_posix()
        image, digest = split_image(manifest.image)
        for tool in manifest.tools:
            if tool.name in BUILTINS:
                raise LockError(f"{relative}: tool '{tool.name}' has the name of a built-in")
            key = f"{tool.name}@{manifest.version}"
            if key in entries:
                raise LockError(f"{relative}: {key} is also provided by {entries[key].manifest}")
            entries[key] = LockEntry(
                toolpack=manifest.toolpack,
                manifest=relative,
                image=image,
                digest=digest,
                manifest_sha256=loaded.sha256,
            )
    return LockFile(tools=dict(sorted(entries.items())))


def render_lock(lock: LockFile) -> str:
    data = lock.model_dump(mode="json")
    body = yaml.safe_dump(data, sort_keys=False, default_flow_style=False, width=1000)
    return LOCK_HEADER + body


def write_lock(root: Path) -> Path:
    path = lock_path(root)
    path.write_text(render_lock(build_lock(root)), encoding="utf-8")
    return path


def lock_is_current(root: Path) -> bool:
    expected = render_lock(build_lock(root))
    path = lock_path(root)
    if not path.is_file():
        return False
    try:
        return read_document(path) == expected
    except DocumentReadError:
        return False


def read_lock(root: Path) -> LockFile:
    path = lock_path(root)
    try:
        data = parse_yaml(read_document(path))
    except DocumentReadError as exc:
        raise LockError(str(exc)) from exc
    except yaml.YAMLError as exc:
        raise LockError(f"{path}: invalid YAML: {yaml_error_message(exc)}") from exc
    try:
        return LockFile.model_validate(data)
    except ModelError as exc:
        first = exc.errors(include_url=False, include_input=False)[0]
        message = f"{format_path(first['loc'])}: {first['msg']}"
        raise LockError(f"{path}: {message} ({exc.error_count()} problem(s))") from exc
